spring.application.name=mailzone

server.port=8085

# Gmail SMTP (runtime config)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mrunmayidhongade000@gmail.com

spring.mail.password=vmzk vcqu zmuc fvie
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
